### ISSUE TITLE
curious about object lifetime recorder

### ISSUE THREAD

**Issue by lynus** [rodrigo-bruno/ng2c#1]
It seems OLR is not included in this repo. I'm very curious about how object graph analyzer works, since your brilliant paper does not give details on how it decide a object should allocted in which generation, and  how it decide a new generation is necessary, besides predefined young/old generation.

**Comment by rodrigo-bruno** [comment]
We decided to continue improving OLR and we are publishing a paper which takes advantage of an improved version of OLR. The paper will be presented  in Middleware 17. You have much more detailed description there.

You can find the code for the improved version at https://github.com/rodrigo-bruno/polm2. The main diference is that the new version detects conflicts when selecting generations and tries to solved them. The code may need some polishment but you can get the idea.

If you dont understant how it works let me know. Anyway, if you are really interested I can send you a copy of the accepted paper as soon as we close it.
