### ISSUE TITLE
curious about is there any modification to Javac

### ISSUE THREAD

**Issue by dumplingsMing** [rodrigo-bruno/ng2c#2]
Hi there!

We are working on a project which also needs to mark out the ```new``` operation of some local variables. However, in our build environment (openjdk 8u102-b14), we haven't seen the ```RetentionPolicy.RUNTIME``` ```ElementType.LOCAL_VARIABLE``` ```@Gen``` annotation appears in the classfile. Even its name doesn't exist in the constant pool of the classfile. So we can do nothing but applied some ugly modification to JVM and JDK to make our project works.

However, I found that it's possible to directly use local variable annotations according to your brilliant paper. So I'm very curious about your openjdk version, the implementation of ```@Gen``` annotation and whether you have modified javac or not, since It seems that the code of ```@Gen``` annotation and javac are not included in this project.

**Comment by rodrigo-bruno** [comment]
Hello!

You don't need to change the javac. Basically we defined a Gen annotation in 

jdk/src/share/classes/java/lang/Gen.java. This file contains:
package java.lang;
import java.lang.annotation.*;
@Target({ElementType.TYPE_USE})
@Retention(value=RetentionPolicy.RUNTIME)
public @interface Gen {}

After adding this file, you should be able to build a Java program and see the annotation in the class file.

Then we changed the class file parsedr in hotspot (https://github.com/rodrigo-bruno/ng2c/commit/5d0eb973c6bca39cf3ee25ae67f49411935aef62#diff-0494b86f3e31e6cfe16818c09546ed96) to save the annotations along side the method metadata (by default these annotations are discarted by the parser).
